name: anumber
description: A new Flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.0.2
  intl: ^0.17.0
  provider: ^6.0.4
  sqflite: ^2.2.4+1
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17
  animated_text_kit: ^4.2.2
  excel: ^2.0.1
  file_picker: ^5.2.5
  audioplayers: ^0.19.1
  line_icons: ^2.0.1
  introduction_screen: any
  flutter_native_splash: any
  # flutter_launcher_icons: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.2.0
  collection: any
  loading_animation_widget: ^1.2.0+4
  skeleton_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  path_animator: ^0.0.1


flutter_native_splash:
  color: 'FAFAFA'
  image: 'assets/images/splash.png'
  fullscreen: true

# flutter_icons:
#   android: true 
#   ios: true
#   image_path: "assets/images/mian.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  assets:
    - assets/images/
    - assets/DB.xlsx
    - assets/button.mp3
    - assets/button2.mp3
    - assets/button3.mp3
    - assets/correct.mp3
    - assets/incorrect.mp3
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Noto Sans JP
    fonts:
      - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Regular.ttf
  # fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
  #       - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.anumber
    iosBundleIdentifier: com.example.anumber
